export const createData = [
    {
      "id" : "lovebabbar",
      "name": "Love Babbar",
      "description": "Love Babbar is a Software Engineer and a Youtuber, primarily known for his Coding and Software Engineering skills. He is quite a popular figure among students as well as working professionals on various social media platforms, his YouTube and LinkedIn profiles amassing almost 1M subscribers. He's alsomentored 500k+ students so far. He has done his B.Tech (IT) from the Netaji Subhash Institute of Technology (NSIT), Delhi, and has worked in Amazon and Microsoft.",
      "dsasheeturl": "https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view",
      "youtubelink": "https://www.youtube.com/@lovebabbar",
      "instalink": "https://www.instagram.com/lovebabbar1/",
      "twitterlink": "https://twitter.com/lovebabbar3",
      "linkedinlink": "https://www.linkedin.com/in/love-babbar-38ab2887/",
      "weburl": "https://www.codehelp.in/",
      "dsafree":"https://www.youtube.com/watch?v=z9bZufPHFLU&list=PLfqMhTWNBTe0b2nM6JHVCnAkhQRGiZMSJ",
      "dsapaid":"https://www.codehelp.in/",
      "numbers": [588000,531805,136000,6571],
      "iframe" : "https://www.youtube.com/embed/4iFALQ1ACdA?si=acm4Dxh6ib8QlbeC",
      "brandname" : "CodeHelp"
    },
    {
      "id" : "amandhattarwal",
      "name": "Aman Dhattarwal",
      "description": "Famous Indian YouTuber, Speaker, Motivator, Educator, Entrepreneur, and Advisor with inspirational and aspiring videos on his channel that helps students to learn how to focus. Founder of “Apni Kaksha” and “Apna College” and has been a TedX speaker 16 times! Most inspiring personality, especially for science students of classes 11th and 12th.",
      "dsasheeturl": "https://docs.google.com/spreadsheets/d/1hXserPuxVoWMG9Hs7y8wVdRCJTcj3xMBAEYUOXQ5Xag/edit#gid=0",
      "youtubelink": "https://www.youtube.com/@ApnaCollegeOfficial",
      "instalink": "https://www.instagram.com/amandhattarwal/",
      "twitterlink": "https://twitter.com/AmanDhattarwal",
      "linkedinlink": "https://www.linkedin.com/in/dhattarwalaman/",
      "weburl": "https://www.apnacollege.in/",
      "dsafree":"https://www.youtube.com/watch?v=z9bZufPHFLU&list=PLfqMhTWNBTe0b2nM6JHVCnAkhQRGiZMSJ",
      "dsapaid":"https://www.apnacollege.in/",
      "numbers": [5090000,322175,578000,107300],
      "iframe" : "https://www.youtube.com/embed/u6Xsayqxij0?si=Zq48Pk8OD8P_SZNs",
      "brandname" : "Apna College"
    },
    {
      "id" : "anujbhaiya",
      "name": "Anuj Kumar Sharma",
      "description": "Software Engineer who has worked with Top Product-based companies like Amazon and Urban Company. Manages his personal YouTube channel named Anuj Bhaiya with a subscriber base of more than 4 Lakh students. Devoted his life to helping students learn coding after leaving his job at Amazon.",
      "dsasheeturl": "https://docs.google.com/spreadsheets/d/1hXserPuxVoWMG9Hs7y8wVdRCJTcj3xMBAEYUOXQ5Xag/edit#gid=0",
      "youtubelink": "https://www.youtube.com/@anujbhaiya",
      "instalink": "https://www.instagram.com/Anuj.Kumar.Sharma",
      "twitterlink": "https://twitter.com/anujbhaiya716",
      "linkedinlink": "https://www.linkedin.com/in/anuj-kumar-sharma-294533138/",
      "weburl": "https://www.codingshuttle.com/",
      "dsafree":"https://www.youtube.com/watch?v=N89PN_uyelU&list=PLUcsbZa0qzu3yNzzAxgvSgRobdUUJvz7p",
      "dsapaid":"https://www.codingshuttle.com/",
      "numbers": [471000,124044,105000,1600],
      "iframe" : "https://www.youtube.com/embed/1dlMv5DMzvc?si=f5PFw0T20tSQxtz2",
      "brandname" : "Coding Shuttle"
  
    },
    {
      "id" : "striver",
      "name": "Striver",
      "description": "Software Engineer at Google who also got offers from Facebook and other startups. Previously worked with Top Product-based companies like Amazon and Media.net. Followed by 1 million+ students across all social media platforms. Founder of Take U Forward.",
      "dsasheeturl": "https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems",
      "youtubelink": "https://www.youtube.com/@takeUforward",
      "instalink": "https://www.instagram.com/striver_79",
      "twitterlink": "https://twitter.com/striver_79",
      "linkedinlink": "https://www.linkedin.com/in/rajstriver/",
      "weburl": "https://takeuforward.org/",
      "dsafree":"https://www.youtube.com/watch?v=0bHoB32fuj0&list=PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz",
      "dsapaid":"https://takeuforward.org/",
      "numbers": [535000,564647,122000,119100],
      "iframe" : "https://www.youtube.com/embed/FwBsi9HEG1Y?si=7MG1o4ZMzaFwrIgL",
      "brandname" : "Take U Forward"
    },
    {
      "id" : "mohammadfraz",
      "name": "Mohd. Fraz",
      "description": "Ex-Googler and dedicated educator known for simplifying DSA. Teaching experience on platforms like Unacademy, CodeChef, Coding Ninjas, NextLeap, and his own YouTube channel. Reached over 500K students, making challenging topics easily understandable.",
      "dsasheeturl": "https://docs.google.com/spreadsheets/d/1-wKcV99KtO91dXdPkwmXGTdtyxAfk1mbPXQg81R9sFE/edit#gid=0",
      "youtubelink": "https://www.youtube.com/@mohammadfraz",
      "instalink": "https://www.instagram.com/frazmohammad/",
      "twitterlink": "https://twitter.com/mohammadfrazX",
      "linkedinlink": "https://www.linkedin.com/in/frazmohammad/",
      "weburl": "https://learnyard.com/courses/dsa",
      "dsafree":"https://www.youtube.com/watch?v=jt-Bj-GsxT8&list=PLKZaSt2df1gxsa7iuGx6ZHzPB8fROUFMz",
      "dsapaid":"https://learnyard.com/courses/dsa",
      "numbers": [428000,227699,62200,30],
      "iframe" : "https://www.youtube.com/embed/NXQi_g1pVqI?si=B0YVSc97tvRF7ZXX",
      "brandname" : "LearnYard"
      
    }
  ]